image: gradle:7.0-jdk-11

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD

before_script:
  - export PROJECT_NAME=regit-backend
  - export IMAGE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle test

deploy:
  stage: deploy
  image: alpine
  script:
    - echo "Deploying the application..."
