image: maven:3.8.1-jdk-11

stages:
  - build
  - test
  - docker-build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - export PROJECT_NAME=regit-backend
  - export IMAGE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - mvn clean package -DskipTests

test:
  stage: test
  script:
    - mvn test

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: alpine
  script:
    - echo "Deploying the application..."
